using DR.Database.ExtendModels;
using Newtonsoft.Json.Linq;

namespace FMS.Models.Dto {
    public class SettingAutoGenerateDto {
        public ESetting Code { get; set; }
        public string DisplayName { get; set; } = string.Empty;
        public string? Description { get; set; }
        public string Prefix { get; set; } = string.Empty;
        public int StartNumber { get; set; }
        public int IncrNumber { get; set; }
        public bool IsRandomIncrNumber { get; set; }
        public EDateTimePeriod? ResetBy { get; set; }

        public JToken ToSettingValue() {
            return JToken.FromObject(new AutoGenerate {
                Prefix = Prefix,
                StartNumber = StartNumber,
                IncrNumber = IncrNumber,
                IsRandomIncrNumber = IsRandomIncrNumber,
                ResetBy = ResetBy,
            });
        }

        public static SettingAutoGenerateDto FromSettingValue(SettingDto dto) {
            var model = dto.Value.ToObject<AutoGenerate>();
            return new SettingAutoGenerateDto {
                Code = dto.Code,
                DisplayName = dto.DisplayName,
                Description = dto.Description,
                Prefix = model?.Prefix ?? string.Empty,
                StartNumber = model?.StartNumber ?? default,
                IncrNumber = model?.IncrNumber ?? default,
                IsRandomIncrNumber = model?.IsRandomIncrNumber ?? default,
                ResetBy = model?.ResetBy,
            };
        }
    }
}
