namespace DR.Constant.Enums;

public enum EAuditDocType {
    Category = 1,
    Customer = 2,
    Supplier = 3,
    Warehouse = 4,
    Store = 5,
    ProductOnStore = 6,
    GeneralSetting = 7,
    WarehouseImport = 8,
    WarehouseExport = 9,
    WarehouseTransfer = 10,
    WarehouseRefund = 11,
    WarehouseAdjustment = 12,
    Product = 13,
    Order = 14,
    User = 15,
    Role = 16,
    PaymentMethod = 17,
    ProductCategory = 18,
    OriginDebt = 19,
    PayDebt = 20,
    ProductOnWarehouse = 21,
    OrderExport = 22,
    OrderRefund = 23,
    CustomerGroup = 24,
    CustomerOnCustomerGroup = 25,
    WarehouseExportOther = 26,
    WarehouseImportOther = 27,
    Receipt = 29,
    Payment = 30,
    Brand = 31,
    CustomerDebt = 32,
    ProductBrand = 33,
}
