namespace DR.Constant.Enums;

public enum ESetting {
    AutoGenerateProductCode = 101,
    AutoGenerateCustomerCode = 102,
    AutoGenerateSupplierCode = 103,
    AutoGenerateStoreCode = 104,
    AutoGenerateWarehouseCode = 105,
    AutoGenerateRoleCode = 106,
    AutoGenerateWarehouseImportCode = 107,
    AutoGenerateWarehouseExportCode = 108,
    AutoGenerateWarehouseTransferCode = 109,
    AutoGenerateWarehouseRefundCode = 110,
    AutoGenerateOrderNo = 111,
    AutoGenerateCategoryCode = 112,
    AutoGenerateWarehouseAdjustmentCode = 113,
    AutoGeneratePaymentMethodCode = 114,
    EmailSettingCode = 115,
    AutoGenerateReceiptCode = 116,
    AutoGeneratePaymentCode = 117,
    AutoGenerateCustomerGroupCode = 118,
    AutoGenerateBrandCode = 119,
    AutoExportOrder = 200,
    NumberFormat = 201,
}
